name: SonarCloud Scan
description: >
  Scan your code with SonarCloud to detect bugs, vulnerabilities and code smells
  in 26+ programming languages.
branding:
  icon: check
  color: green
runs:
  using: composite
  steps:
#    - name: Restore sonarcloud Image Cache if it exists
#      id: cache-docker-sonarcloud
#      uses: actions/cache@v3
#      with:
#        path: ~/ci/cache/docker/sonarcloud
#        key: cache-docker-sonarcloud
#
#    - name: Update sonarcloud Image Cache if cache miss
#      if: steps.cache-docker-sonarcloud.outputs.cache-hit != 'true'
#      shell: bash
#      run: |
#        docker pull 885420015722.dkr.ecr.ap-southeast-1.amazonaws.com/sonar-cloud:scanner-cli-5.0
#        mkdir -p ~/ci/cache/docker/sonarcloud
#        docker image save 885420015722.dkr.ecr.ap-southeast-1.amazonaws.com/sonar-cloud:scanner-cli-5.0 \
#        --output ~/ci/cache/docker/sonarcloud/scanner-cli-5.0.tar
#
#    - name: Use sonarcloud Image Cache if cache hit
#      if: steps.cache-docker-sonarcloud.outputs.cache-hit == 'true'
#      shell: bash
#      run: docker image load --input ~/ci/cache/docker/sonarcloud/scanner-cli-5.0.tar

    - name: Build docker image
      shell: bash
      run: |
        docker build \
        --tag sonarcloud:latest \
        --file ${{github.action_path}}/Dockerfile ${{github.action_path}}

    - name: Run sonarcloud scanner
      shell: bash
      run: |
        docker run --workdir /github/workspace --rm \
        -e INPUT_PROJECTBASEDIR="${{inputs.projectBaseDir}}" \
        -e INPUT_ARGS="${{inputs.args}}" \
        -e SONAR_TOKEN="${{env.SONAR_TOKEN}}" \
        -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" \
        -e "AWS_CLI_VERSION" -e "AWS_CLI_ARCH" -e "VERBOSE" -e "LIGHTSAILCTL" -e "BINDIR" -e "INSTALLROOTDIR" -e "ROOTDIR" \
        -e "WORKDIR" -e "GITHUB_TOKEN" -e "SONAR_TOKEN" -e "INPUT_ARGS" -e "INPUT_PROJECTBASEDIR" -e "HOME" -e "GITHUB_JOB" \
        -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" \
        -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" \
        -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" \
        -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" \
        -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" \
        -e "GITHUB_WORKSPACE" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" \
        -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" \
        -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" \
        -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" \
        -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true \
        -e CI=true --entrypoint "/entrypoint.sh" \
        -v "/var/run/docker.sock":"/var/run/docker.sock" \
        -v "/runner/_work/_temp/_github_home":"/github/home" \
        -v "/runner/_work/_temp/_github_workflow":"/github/workflow" \
        -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" \
        -v ${{github.workspace}}:"/github/workspace" \
        sonarcloud:latest

inputs:
  args:
    description: Additional arguments to the sonarcloud scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
