name: SonarCloud Scan
description: >
  Scan your code with SonarCloud to detect bugs, vulnerabilities and code smells
  in 26+ programming languages.
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
  args:
    CONTAINER_REGISTRY: ${{ inputs.containerRegistry }}
inputs:
  args:
    description: Additional arguments to the sonarcloud scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
  containerRegistry:
    description: Set the container registry to pull the sonar scanner image
    required: false
    default: dockerhub.io
